# Generated by Django 3.2.13 on 2022-06-22 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_bow_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bow',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bow',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='posts', serialize=False, to='pages.post'),
        ),
    ]
